@startuml controller
interface IUsuarioController <<interface>> {
      + User create(usuario)
      + boolean login(usuario)
}
class UserController{
      + User create(user)
      + boolean login(user)
}

@enduml