@startuml
allow_mixing

package "Gestor de Mídias" {
    package "persistence"{
        
        !include persistenceClasses.plantuml

        Usuario o-- Conta : 0..*
        Usuario o-- Midia : 0..*
        
    }
    package "persistencelayer"{
        package "DAO"{

            !include persistenceClassesAndInterface.plantuml
            
            IUsuarioDAO <|..left UsuarioDAO_Mongoose
            IContaDAO <|..left ContaDAO_Mongoose
            IMidiaDAO <|..left MidiaDAO_Mongoose
            
        }
       
        package "controller"{
       
           interface IUsuarioController <<interface>> {
                 + User create(usuario)
                 + boolean login(usuario)
                  }
            class UserController{
                  + User create(user)
                  + boolean login(user)
                  }
          IUserController <|..left UserController        
        }
        package "model"{
            json "UserSchema" as userschema {
                "id"  : "",
                "email" : "",
                "password": "",
                "status" : "false"
            }
        }
    }
    package "servicelayer" {
        package "View"{
            interface IRoutes {
                +void createroutes()
            }
            class UserRoutes {
                +void createroutes()
            }
            IRoutes <|.. UserRoutes
        }
        package "DTO"{
            json "UserLoginReq" as userloginreq {
                "email" : "",
                "password": ""
            }
            json "UserLoginRes" as userloginres {
                "msgcode" : "001",
                "userobject": "{}"
            }
            json "UserCreateReq" as usercreatereq{
                "email" : "",
                "password": "",
                "confpassword": ""
            }
            json "UserCreateRes" as usercreateres{
                "msgcode" : "002",
                "userobject": "{}"
            }

        }

    }

}

persistence -[hidden]--> persistencelayer
persistencelayer -[hidden]--> servicelayer

DAO -[hidden]--> model
model -[hidden]--> controller


''View -[hidden]--> DTO

@enduml