            interface IUsuarioDAO <<interface>> {
                 + boolean create(usuario)
                 + List<usuario> find()
                 + boolean delete(usuario)
                 + boolean update(usuario) 
                  }
            
            class UsuarioDAO_Mongoose {

                 + boolean create(usuario)
                 + List<usuario> find()
                 + boolean delete(usuario)
                 + boolean update(usuario)
                   }
            
            interface IContaDAO <<interface>> {
                 + boolean create(conta)
                 + List<conta> find()
                 + boolean delete(conta)
                 + boolean update(conta) 
                  }
            
            class ContaDAO_Mongoose {
                + boolean create(conta)
                + List<conta> find()
                + boolean delete(conta)
                + boolean update(conta) 
                    }
            
            interface IMidiaDAO <<interface>> {
                 + boolean create(Midia)
                 + List<Midia> find()
                 + boolean delete(Midia)
                 + boolean update(Midia) 
                  }
            
            class MidiaDAO_Mongoose {
                    + boolean create(Midia)
                    + List<Midia> find()
                    + boolean delete(Midia)
                    + boolean update(Midia) 
                    }